<?php
namespace BRG;

const OPTION_SETUP = 100;
const OPTION_SETUP_BEGINNER = 0;
const OPTION_SETUP_STANDARD = 1;
const OPTION_SETUP_FREE = 2;
const OPTION_SETUP_SEED = 3;

const OPTION_EXPANSION_LWP = 101;
const OPTION_EXPANSION_LWP_OFF = 0;
const OPTION_EXPANSION_LWP_ON = 1;

const OPTION_AUTOMA = 105;

const RANDOM = 0;
const OPTION_COMPANY_1 = 106;
const OPTION_COMPANY_2 = 107;
const OPTION_COMPANY_3 = 108;
const OPTION_COMPANY_4 = 109;
const OPTION_COMPANY_5 = 110;

const OPTION_AUTOMA_1 = 111;
const OPTION_AUTOMA_2 = 112;
const OPTION_AUTOMA_3 = 113;
const OPTION_AUTOMA_4 = 114;

const OPTION_LVL_AUTOMA_1 = 115;
const OPTION_LVL_AUTOMA_2 = 116;
const OPTION_LVL_AUTOMA_3 = 117;
const OPTION_LVL_AUTOMA_4 = 118;

const AUTOMA_EASY = 0;
const AUTOMA_MEDIUM = 1;
const AUTOMA_HARD = 2;
const AUTOMA_EXTRA_HARD = 3;

const COMPANY_USA = 1;
const COMPANY_GERMANY = 2;
const COMPANY_ITALY = 3;
const COMPANY_FRANCE = 4;
const COMPANY_NETHERLANDS = 5;


/**
 * User preferences
 */
const OPTION_CONFIRM = 103;
const OPTION_CONFIRM_DISABLED = 0;
const OPTION_CONFIRM_TIMER = 1;
const OPTION_CONFIRM_ENABLED = 2;
